### ISSUE TITLE
Terminal leaves in the HTM (ie actions) should have an empty `combination` field

### ISSUE THREAD

**Issue by alecive** [ScazLab/rpi_integration#10]
Again, very minor , but as per title: terminal leaves (ie actions) should have an empty `combination` field. The `combination` field tells what to do with the children, but if there are no children, it should be left empty (or `null` or whatever)

**Comment by drjesseenglish** [comment]
I've pushed the latest image with this change.

**Comment by alecive** [comment]
It works! Thanks!
