### ISSUE TITLE
Action Implementations

### ISSUE THREAD

**Issue by JakeBrawer** [ScazLab/rpi_integration#4]
While doing the unittests I realized the following actions were not listed as available actions, but are nonetheless needed:
- [ ] get-top-bracket
- [ ] get-top-dowel
- [ ] hold-top-dowel

**Comment by drjesseenglish** [comment]
I'll cover these, as well as release-top-dowel; are there any others you need to not be utterances?

**Comment by alecive** [comment]
For now, I don't think so

**Comment by alecive** [comment]
@JakeBrawer when you fix this and close the issue, please also update the `README.md` file!
