### ISSUE TITLE
Online learning

### ISSUE THREAD

**Issue by JakeBrawer** [ScazLab/rpi_integration#7]
Right, now the learner does not seem capable of learning online. E.g., The following Json input
 ```[["u", "We will build a leg."], ["a", "get-dowel"], ["a", "get-bracket-foot"]]```

Results in this output:

```
{"nodes": {"id": 0, "parent": null, "name": "Start", "combination": "Sequential", "attributes": [], "children": [{"id": 1, "parent": 0, "name": "BUILD ARTIFACT-LEG", "combination": "Sequential", "attributes": [], "children": [{"id": 2, "parent": 1, "name": "ROBOT GET(dowel)", "combination": "Sequential", "attributes": [], "children": []}, {"id": 3, "parent": 1, "name": "ROBOT GET(FOOT_BRACKET)", "combination": "Sequential", "attributes": [], "children": []}]}]}}
```

But when I post to the learner sequentially, e.g.: `[["u", "We will build a leg."], ["a", "get-dowel"]]` and `[["a", "get-bracket-foot"]]` I get this output:

```
{"nodes": {"id": 0, "parent": null, "name": "Start", "combination": "Sequential", "attributes": [], "children": [{"id": 1, "parent": 0, "name": "BUILD ARTIFACT-LEG", "combination": "Sequential", "attributes": [], "children": [{"id": 2, "parent": 1, "name": "ROBOT GET(dowel)", "combination": "Sequential", "attributes": [], "children": []}]}]}}
```

which is missing GET(bracket-foot).

**Comment by drjesseenglish** [comment]
I can't replicate this.  Posting those two sequences sequentially (utterance, action) and then (action) produces the correct result.  Can you provide any more context?

**Comment by alecive** [comment]
> I can't replicate this.

You can't replicate this on your side with your unit tests only, or with the full integration tests?

**Comment by drjesseenglish** [comment]
Running the services with the compose file and posting to the /learn endpoint on my machine produces the correct results.

**Comment by JakeBrawer** [comment]
You are right. I think the issue is just my ignorance of http :cry:

**Comment by drjesseenglish** [comment]
Ah ok - did you sort it out?

**Comment by JakeBrawer** [comment]
I fixed it. I made a stupid typo. Sorry for waisting your time.
