### ISSUE TITLE
Object Names in HTM

### ISSUE THREAD

**Issue by JakeBrawer** [ScazLab/rpi_integration#8]
The HTM doees not produce specific enough names for the robot to use. E.g. get-bracket-back-right results in GET(bracket), but so does get-bracket-front, despite them being different pieces. 

Here are a list of actions and suggested names to be implemented:
- [ ] get-bracket-back-right -> GET(bracket-back-right)
- [ ] get-bracket-back-left ->   GET(bracket-back-left)
- [ ] get-bracket-front ->         GET(bracket-front)
- [ ] get-top-bracket ->           GET(bracket-top)
- [ ] get-top-dowel ->             GET(dowel-top)

**Comment by drjesseenglish** [comment]
These should be fixed in the latest image that was pushed.

**Comment by drjesseenglish** [comment]
(Note I'm specifically accounting for these 5 examples - if others are needed, they will need to be added as well).

**Comment by JakeBrawer** [comment]
Nice! Thanks!
