### ISSUE TITLE
Last part of full chair task

### ISSUE THREAD

**Issue by alecive** [ScazLab/rpi_integration#9]
Ok so this it the latest status of the issue.

With this input sequence:

```
[
    ["u", "We will build a chair."],
        ["u", "I need a screwdriver to assemble a chair."],
            ["a", "get-screwdriver"],
        ["u", "Now we will assemble the seat."],
            ["u", "First, we will build the front leg of the chair."],
                ["a", "get-bracket-foot"],
                ["a", "get-bracket-front"],
                ["a", "get-dowel"],
                ["a", "hold-dowel"],
                ["u", "I am using the screwdriver to affix the brackets on the dowel with screws."],
                ["a", "release-dowel"],
            ["u", "We have assembled a front leg."],
            ["u", "Now, another front leg."],
                ["a", "get-bracket-foot"],
                ["a", "get-bracket-front"],
                ["a", "get-dowel"],
                ["a", "hold-dowel"],
                ["u", "I am putting another set of brackets on the dowel."],
                ["a", "release-dowel"],
            ["u", "I have assembled another front chair leg."],
            ["u", "Now, the back leg on the right side."],
                ["a", "get-bracket-foot"],
                ["a", "get-bracket-back-right"],
                ["a", "get-dowel"],
                ["a", "hold-dowel"],
                ["u", "I am putting the third set of brackets on a dowel."],
                ["a", "release-dowel"],
            ["u", "I have assembled the back leg on the right side of the chair."],
                ["a", "get-bracket-foot"],
                ["a", "get-bracket-back-left"],
                ["a", "get-dowel"],
                ["a", "hold-dowel"],
                ["u", "I am putting the fourth set of brackets on a dowel."],
                ["a", "release-dowel"],
            ["u", "I have assembled the back leg on the left side of the chair"],
            ["u", "Now we affix the legs to the seat."],
                ["a", "get-seat"],
                ["a", "hold-seat"],
                ["u", "I am affixing the four legs to the seat."],
            ["u", "Finished."],
        ["u", "We have assembled the seat."],
        ["u", "Now we will assemble the back."],
            ["u", "First, we assemble the top of the back."],
                ["a", "get-top-bracket"],
                ["a", "get-top-bracket"],
                ["a", "get-top-dowel"],
                ["a", "hold-top-dowel"],
                ["u", "I am affixing the top brackets on the top dowel."],
                ["a", "release-top-dowel"],
            ["u", "We have assembled the top of the back."],
            ["u", "Now, we affix the verticals."],
                ["u", "We will affix a vertical piece."],
                    ["a", "get-dowel"],
                    ["a", "hold-dowel"],
                    ["u", "I am inserting this dowel into the back bracket on the right side to make one vertical piece."],
                ["u", "I have made one vertical piece."],
                ["u", "We will affix another vertical piece."],
                    ["a", "get-dowel"],
                    ["a", "hold-dowel"],
                    ["u", "I am inserting the dowel into the back bracket on the left side to make another vertical piece."],
                ["u", "Now we must affix the back to the vertical pieces."],
                    ["a", "hold-back"],
            ["u", "Done with the verticals."],
            ["u", "I am affixing the top brackets to the back of the chair."],
                ["a", "get-back"],
                ["a", "hold-back"],
                ["u", "Release the back."],
                ["u", "Finished."],
            ["u", "We have affixed the top brackets to the back of the chair."],
        ["u", "We have assembled the back of the chair."],
    ["u", "We finished assembling the chair."]
]
```

We get a good enough HTM on the high level. The problem is the last part of the back. As I mentioned before, there are tons of subtasks that are named in the same exact way (FASTEN ARTIFACT) and do not provide any meaningful information:

![image](https://user-images.githubusercontent.com/4378663/40182962-997ec7c2-59ba-11e8-89ce-37348be14ddc.png)

In this case, some of them should be about affixing "verticals" and then I would need one subtask about affixing the top bracket to the back of the chair.

Also, when does this come from?

![image](https://user-images.githubusercontent.com/4378663/40183234-505f905c-59bb-11e8-83d2-7c860485ed08.png)

What should the human do in this case? I am unable to trace it back to the input sequence above.

**Comment by drjesseenglish** [comment]
In the cases of FASTEN ARTIFACT, if the top one was FASTEN VERTICAL ARTIFACTs and the two lower ones were FASTEN VERTICAL ARTIFACT, would that be sufficient?

**Comment by alecive** [comment]
Yes! It seems more clear to me. Also, maybe the last one could be FASTEN BACK TO TOP or FASTEN TOP or FASTEN TO TOP?

**Comment by drjesseenglish** [comment]
How about this naming (throughout):

+root
  +BUILD CHAIR
    +REQUEST-ACTION GIVE SCREWDRIVER
      -[1]ROBOT GET(screwdriver)
    +BUILD SEAT
      +BUILD ARTIFACT-LEG
        -[1]ROBOT GET(FOOT_BRACKET)
        -[2]ROBOT GET(bracket)
        -[3]ROBOT GET(dowel)
        -[4]ROBOT HOLD(dowel)
        -[5]HUMAN FASTEN(brackets)
        -[6]ROBOT RELEASE(dowel)
      +BUILD ARTIFACT-LEG
        -[1]ROBOT GET(FOOT_BRACKET)
        -[2]ROBOT GET(bracket)
        -[3]ROBOT GET(dowel)
        -[4]ROBOT HOLD(dowel)
        -[5]HUMAN FASTEN(putting)
        -[6]ROBOT RELEASE(dowel)
      +BUILD ARTIFACT-LEG
        -[1]ROBOT GET(FOOT_BRACKET)
        -[2]ROBOT GET(bracket)
        -[3]ROBOT GET(dowel)
        -[4]ROBOT HOLD(dowel)
        -[5]HUMAN FASTEN(putting)
        -[6]ROBOT RELEASE(dowel)
      +BUILD ARTIFACT-LEG
        -[1]ROBOT GET(FOOT_BRACKET)
        -[2]ROBOT GET(bracket)
        -[3]ROBOT GET(dowel)
        -[4]ROBOT HOLD(dowel)
        -[5]HUMAN FASTEN(putting)
        -[6]ROBOT RELEASE(dowel)
      +FASTEN ARTIFACT-LEGs TO SEAT
        -[1]ROBOT GET(seat)
        -[2]ROBOT HOLD(seat)
        -[3]HUMAN FASTEN(legs)
        -[4]ROBOT RELEASE(seat)
    +BUILD BACK-OF-OBJECT
      +BUILD TOP-OF-OBJECT
        -[1]ROBOT GET(bracket)
        -[1]ROBOT GET(bracket)
        -[3]ROBOT GET(dowel)
        -[4]ROBOT HOLD(dowel)
        -[5]HUMAN FASTEN(brackets)
        -[6]ROBOT RELEASE(dowel)
      +FASTEN VERTICAL ARTIFACTs
        +FASTEN VERTICAL ARTIFACT
          -[1]ROBOT GET(dowel)
          -[2]ROBOT HOLD(dowel)
          -[3]HUMAN INSERT(dowel)
          -[4]ROBOT RELEASE(dowel)
        +FASTEN VERTICAL ARTIFACT
          -[1]ROBOT GET(dowel)
          -[2]ROBOT HOLD(dowel)
          -[3]HUMAN INSERT(dowel)
          -[4]ROBOT RELEASE(dowel)
      +FASTEN BACK-OF-OBJECT TO ARTIFACT
        -[1]ROBOT HOLD(back)
        -[2]ROBOT RELEASE(back)
      +FASTEN TOP ARTIFACTs TO BACK-OF-OBJECT
        -[1]HUMAN FASTEN(brackets)
        -[2]ROBOT GET(back)
        -[3]ROBOT HOLD(back)
        -[4]ROBOT RELEASE(back)

**Comment by alecive** [comment]
It seems much better to me!

**Comment by alecive** [comment]
No wait a second, the robot in this case does a `hold` before getting the object. Let me check.

**Comment by alecive** [comment]
Ok yes there's a problem with my sequence, but it should not be changing much

**Comment by alecive** [comment]
Theoretically, `[1]HUMAN FASTEN(brackets)` should appear after `[3]ROBOT HOLD(back)`

**Comment by drjesseenglish** [comment]
I pushed the image with these naming changes.  WRT to the FASTEN BACK node, I can see that is coming from these inputs:
["u", "Now we must affix the back to the vertical pieces."],
       ["a", "hold-back"],

First, we should probably change these inputs to actually include human activity (and probably some "finished" statement as well).  But further, I can see that the learner isn't putting this information in the right location (which is probably why it looks off to you).  That will involve work on the learner heuristics - I'll see what I can do.

**Comment by alecive** [comment]
Sounds good 
I will try it right away

**Comment by drjesseenglish** [comment]
How does this look (with a little heuristic work and adding a few extra utterances, I think that random floating FASTEN BACK is in a more sensical place, with human actions):

`+root
  +BUILD CHAIR
    +REQUEST-ACTION GIVE SCREWDRIVER
      -[1]ROBOT GET(screwdriver)
    +BUILD SEAT
      +BUILD ARTIFACT-LEG
        -[1]ROBOT GET(FOOT_BRACKET)
        -[2]ROBOT GET(bracket-front)
        -[3]ROBOT GET(dowel)
        -[4]ROBOT HOLD(dowel)
        -[5]HUMAN FASTEN(brackets)
        -[6]ROBOT RELEASE(dowel)
      +BUILD ARTIFACT-LEG
        -[1]ROBOT GET(FOOT_BRACKET)
        -[2]ROBOT GET(bracket-front)
        -[3]ROBOT GET(dowel)
        -[4]ROBOT HOLD(dowel)
        -[5]HUMAN FASTEN(brackets)
        -[6]ROBOT RELEASE(dowel)
      +BUILD ARTIFACT-LEG
        -[1]ROBOT GET(FOOT_BRACKET)
        -[2]ROBOT GET(bracket-back-right)
        -[3]ROBOT GET(dowel)
        -[4]ROBOT HOLD(dowel)
        -[5]HUMAN FASTEN(brackets)
        -[6]ROBOT RELEASE(dowel)
      +BUILD ARTIFACT-LEG
        -[1]ROBOT GET(FOOT_BRACKET)
        -[2]ROBOT GET(bracket-back-left)
        -[3]ROBOT GET(dowel)
        -[4]ROBOT HOLD(dowel)
        -[5]HUMAN FASTEN(brackets)
        -[6]ROBOT RELEASE(dowel)
      +FASTEN ARTIFACT-LEGs TO SEAT
        -[1]ROBOT GET(seat)
        -[2]ROBOT HOLD(seat)
        -[3]HUMAN FASTEN(legs)
        -[4]ROBOT RELEASE(seat)
    +BUILD BACK-OF-OBJECT
      +BUILD TOP-OF-OBJECT
        -[1]ROBOT GET(bracket-top)
        -[1]ROBOT GET(bracket-top)
        -[3]ROBOT GET(dowel-top)
        -[4]ROBOT HOLD(dowel)
        -[5]HUMAN FASTEN(brackets)
        -[6]ROBOT RELEASE(dowel)
      +FASTEN VERTICAL ARTIFACTs
        +FASTEN VERTICAL ARTIFACT
          -[1]ROBOT GET(dowel)
          -[2]ROBOT HOLD(dowel)
          -[3]HUMAN INSERT(dowel)
          -[4]ROBOT RELEASE(dowel)
        +FASTEN VERTICAL ARTIFACT
          -[1]ROBOT GET(dowel)
          -[2]ROBOT HOLD(dowel)
          -[3]HUMAN INSERT(dowel)
          -[4]ROBOT RELEASE(dowel)
        +FASTEN BACK-OF-OBJECT TO ARTIFACT
          -[1]ROBOT HOLD(back)
          -[2]HUMAN FASTEN(back)
          -[3]ROBOT RELEASE(back)
      +FASTEN TOP ARTIFACTs TO BACK-OF-OBJECT
        -[1]HUMAN FASTEN(brackets)
        -[2]ROBOT GET(back)
        -[3]ROBOT HOLD(back)
        -[4]ROBOT RELEASE(back)`

`input = [
            ["u", "We will build a chair."],
                ["u", "I need a screwdriver to assemble a chair."],
                    ["a", "get-screwdriver"],
                ["u", "Now we will assemble the seat."],
                    ["u", "First, we will build the front leg of the chair."],
                        ["a", "get-bracket-foot"],
                        ["a", "get-bracket-front"],
                        ["a", "get-dowel"],
                        ["a", "hold-dowel"],
                        ["u", "I am using the screwdriver to affix the brackets on the dowel with screws."],
                        ["a", "release-dowel"],
                    ["u", "We have assembled a front leg."],
                    ["u", "Now, another front leg."],
                        ["a", "get-bracket-foot"],
                        ["a", "get-bracket-front"],
                        ["a", "get-dowel"],
                        ["a", "hold-dowel"],
                        ["u", "I am putting another set of brackets on the dowel."],
                        ["a", "release-dowel"],
                    ["u", "I have assembled another front chair leg."],
                    ["u", "Now, the back leg on the right side."],
                        ["a", "get-bracket-foot"],
                        ["a", "get-bracket-back-right"],
                        ["a", "get-dowel"],
                        ["a", "hold-dowel"],
                        ["u", "I am putting the third set of brackets on a dowel."],
                        ["a", "release-dowel"],
                    ["u", "I have assembled the back leg on the right side of the chair."],
                        ["a", "get-bracket-foot"],
                        ["a", "get-bracket-back-left"],
                        ["a", "get-dowel"],
                        ["a", "hold-dowel"],
                        ["u", "I am putting the fourth set of brackets on a dowel."],
                        ["a", "release-dowel"],
                    ["u", "I have assembled the back leg on the left side of the chair"],
                    ["u", "Now we affix the legs to the seat."],
                        ["a", "get-seat"],
                        ["a", "hold-seat"],
                        ["u", "I am affixing the four legs to the seat."],
                    ["u", "Finished."],
                ["u", "We have assembled the seat."],
                ["u", "Now we will assemble the back."],
                    ["u", "First, we assemble the top of the back."],
                        ["a", "get-top-bracket"],
                        ["a", "get-top-bracket"],
                        ["a", "get-top-dowel"],
                        ["a", "hold-top-dowel"],
                        ["u", "I am affixing the top brackets on the top dowel."],
                        ["a", "release-top-dowel"],
                    ["u", "We have assembled the top of the back."],
                    ["u", "Now, we affix the verticals."],
                        ["u", "We will affix a vertical piece."],
                            ["a", "get-dowel"],
                            ["a", "hold-dowel"],
                            ["u", "I am inserting this dowel into the back bracket on the right side to make one vertical piece."],
                        ["u", "I have made one vertical piece."],
                        ["u", "We will affix another vertical piece."],
                            ["a", "get-dowel"],
                            ["a", "hold-dowel"],
                            ["u", "I am inserting the dowel into the back bracket on the left side to make another vertical piece."],
                        ["u", "I have made another vertical piece."],
                        ["u", "Now we must affix the back to the vertical pieces."],
                            ["a", "hold-back"],
                            ["u", "I am affixing the back to the vertical pieces."],
                        ["u", "We have affixed the back."],
                    ["u", "Done with the verticals."],
                    ["u", "I am affixing the top brackets to the back of the chair."],
                        ["a", "get-back"],
                        ["a", "hold-back"],
                        ["u", "Release the back."],
                        ["u", "Finished."],
                    ["u", "We have affixed the top brackets to the back of the chair."],
                ["u", "We have assembled the back of the chair."],
            ["u", "We finished assembling the chair."]
        ]`

**Comment by alecive** [comment]
@drjesseenglish I am trying to run the input sequence myself, but it fails. Any suggestions?

**Comment by drjesseenglish** [comment]
Yeah it requires updates that I haven't pushed yet.  Was seeing if you thought this was a satisfactory output.

**Comment by alecive** [comment]
Ah sorry yes that seems very satisfactory to me! I would just move `["a", "get-back"],` before `["a", "hold-back"],` (ie right after `["u", "Now we must affix the back to the vertical pieces."],`).

The only thing that seems odd is this one (at the very end):

```
      +FASTEN TOP ARTIFACTs TO BACK-OF-OBJECT
        -[1]HUMAN FASTEN(brackets)
        -[2]ROBOT GET(back)
        -[3]ROBOT HOLD(back)
        -[4]ROBOT RELEASE(back)
```

According to this, the human is supposed to assemble parts before the robot holds the human to help him doing the assembly.
I would like to have the following (also, I removed GET(back) since I would move it up as I said before:

```
      +FASTEN TOP ARTIFACTs TO BACK-OF-OBJECT
        -[1]ROBOT HOLD(back)
        -[2]HUMAN FASTEN(brackets)
        -[3]ROBOT RELEASE(back)
```

**Comment by drjesseenglish** [comment]
How about this take (I think I understood both of your comments):

```
+root
  +BUILD CHAIR
    +REQUEST-ACTION GIVE SCREWDRIVER
      -[1]ROBOT GET(screwdriver)
    +BUILD SEAT
      +BUILD ARTIFACT-LEG
        -[1]ROBOT GET(FOOT_BRACKET)
        -[2]ROBOT GET(bracket-front)
        -[3]ROBOT GET(dowel)
        -[4]ROBOT HOLD(dowel)
        -[5]HUMAN FASTEN(brackets)
        -[6]ROBOT RELEASE(dowel)
      +BUILD ARTIFACT-LEG
        -[1]ROBOT GET(FOOT_BRACKET)
        -[2]ROBOT GET(bracket-front)
        -[3]ROBOT GET(dowel)
        -[4]ROBOT HOLD(dowel)
        -[5]HUMAN FASTEN(brackets)
        -[6]ROBOT RELEASE(dowel)
      +BUILD ARTIFACT-LEG
        -[1]ROBOT GET(FOOT_BRACKET)
        -[2]ROBOT GET(bracket-back-right)
        -[3]ROBOT GET(dowel)
        -[4]ROBOT HOLD(dowel)
        -[5]HUMAN FASTEN(brackets)
        -[6]ROBOT RELEASE(dowel)
      +BUILD ARTIFACT-LEG
        -[1]ROBOT GET(FOOT_BRACKET)
        -[2]ROBOT GET(bracket-back-left)
        -[3]ROBOT GET(dowel)
        -[4]ROBOT HOLD(dowel)
        -[5]HUMAN FASTEN(brackets)
        -[6]ROBOT RELEASE(dowel)
      +FASTEN ARTIFACT-LEGs TO SEAT
        -[1]ROBOT GET(seat)
        -[2]ROBOT HOLD(seat)
        -[3]HUMAN FASTEN(legs)
        -[4]ROBOT RELEASE(seat)
    +BUILD BACK-OF-OBJECT
      +BUILD TOP-OF-OBJECT
        -[1]ROBOT GET(bracket-top)
        -[1]ROBOT GET(bracket-top)
        -[3]ROBOT GET(dowel-top)
        -[4]ROBOT HOLD(dowel)
        -[5]HUMAN FASTEN(brackets)
        -[6]ROBOT RELEASE(dowel)
      +FASTEN VERTICAL ARTIFACTs
        +FASTEN VERTICAL ARTIFACT
          -[1]ROBOT GET(dowel)
          -[2]ROBOT HOLD(dowel)
          -[3]HUMAN INSERT(dowel)
          -[4]ROBOT RELEASE(dowel)
        +FASTEN VERTICAL ARTIFACT
          -[1]ROBOT GET(dowel)
          -[2]ROBOT HOLD(dowel)
          -[3]HUMAN INSERT(dowel)
          -[4]ROBOT RELEASE(dowel)
        +FASTEN BACK-OF-OBJECT TO ARTIFACT
          -[1]ROBOT GET(back)
          -[2]ROBOT HOLD(back)
          -[3]HUMAN FASTEN(back)
          -[4]ROBOT RELEASE(back)
      +FASTEN TOP ARTIFACTs TO BACK-OF-OBJECT
        -[1]ROBOT GET(back)
        -[2]ROBOT HOLD(back)
        -[3]HUMAN FASTEN(brackets)
        -[4]ROBOT RELEASE(back)
```

```
input = [
            ["u", "We will build a chair."],
                ["u", "I need a screwdriver to assemble a chair."],
                    ["a", "get-screwdriver"],
                ["u", "Now we will assemble the seat."],
                    ["u", "First, we will build the front leg of the chair."],
                        ["a", "get-bracket-foot"],
                        ["a", "get-bracket-front"],
                        ["a", "get-dowel"],
                        ["a", "hold-dowel"],
                        ["u", "I am using the screwdriver to affix the brackets on the dowel with screws."],
                        ["a", "release-dowel"],
                    ["u", "We have assembled a front leg."],
                    ["u", "Now, another front leg."],
                        ["a", "get-bracket-foot"],
                        ["a", "get-bracket-front"],
                        ["a", "get-dowel"],
                        ["a", "hold-dowel"],
                        ["u", "I am putting another set of brackets on the dowel."],
                        ["a", "release-dowel"],
                    ["u", "I have assembled another front chair leg."],
                    ["u", "Now, the back leg on the right side."],
                        ["a", "get-bracket-foot"],
                        ["a", "get-bracket-back-right"],
                        ["a", "get-dowel"],
                        ["a", "hold-dowel"],
                        ["u", "I am putting the third set of brackets on a dowel."],
                        ["a", "release-dowel"],
                    ["u", "I have assembled the back leg on the right side of the chair."],
                        ["a", "get-bracket-foot"],
                        ["a", "get-bracket-back-left"],
                        ["a", "get-dowel"],
                        ["a", "hold-dowel"],
                        ["u", "I am putting the fourth set of brackets on a dowel."],
                        ["a", "release-dowel"],
                    ["u", "I have assembled the back leg on the left side of the chair"],
                    ["u", "Now we affix the legs to the seat."],
                        ["a", "get-seat"],
                        ["a", "hold-seat"],
                        ["u", "I am affixing the four legs to the seat."],
                    ["u", "Finished."],
                ["u", "We have assembled the seat."],
                ["u", "Now we will assemble the back."],
                    ["u", "First, we assemble the top of the back."],
                        ["a", "get-top-bracket"],
                        ["a", "get-top-bracket"],
                        ["a", "get-top-dowel"],
                        ["a", "hold-top-dowel"],
                        ["u", "I am affixing the top brackets on the top dowel."],
                        ["a", "release-top-dowel"],
                    ["u", "We have assembled the top of the back."],
                    ["u", "Now, we affix the verticals."],
                        ["u", "We will affix a vertical piece."],
                            ["a", "get-dowel"],
                            ["a", "hold-dowel"],
                            ["u", "I am inserting this dowel into the back bracket on the right side to make one vertical piece."],
                        ["u", "I have made one vertical piece."],
                        ["u", "We will affix another vertical piece."],
                            ["a", "get-dowel"],
                            ["a", "hold-dowel"],
                            ["u", "I am inserting the dowel into the back bracket on the left side to make another vertical piece."],
                        ["u", "I have made another vertical piece."],
                        ["u", "Now we must affix the back to the vertical pieces."],
                            ["a", "get-back"],
                            ["a", "hold-back"],
                            ["u", "I am affixing the back to the vertical pieces."],
                        ["u", "We have affixed the back."],
                    ["u", "Done with the verticals."],
                    ["u", "Now, we affix the top brackets to the back of the chair."],
                        ["a", "get-back"],
                        ["a", "hold-back"],
                        ["u", "I am affixing the top brackets to the back of the chair."],
                        ["u", "Release the back."],
                        ["u", "Finished."],
                    ["u", "We have affixed the top brackets to the back of the chair."],
                ["u", "We have assembled the back of the chair."],
            ["u", "We finished assembling the chair."]
        ]
```

**Comment by drjesseenglish** [comment]
It is up.

**Comment by alecive** [comment]
That's much better! Thanks @drjesseenglish
